[package]
name = "bebops"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
eframe = "0.23.0"
id3 = "1.8.0"
rfd = "0.12.1"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
